<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<div class="actions-toolbar-left">
</div>
<div class="actions-toolbar">
    <div class="primary">
        <button id="btn_save_product" type="button"
            class="action submit primary"
            title="<?php echo __('Publish ticket') ?>">
            <span><?php echo __('Publish ticket') ?></span>
        </button>
        
        <p><?php echo iconv('ISO-8859-1', 'UTF-8', __('Ao publicar o bilhete, você aceita e aceita os')); ?> <a target="_blank" href="<?php echo $this->getUrl('terms-and-policies')?>"><?php echo iconv('ISO-8859-1', 'UTF-8', __('termos e as políticas')); ?></a> <?php echo iconv('ISO-8859-1', 'UTF-8', __('da venda de ja ê!')); ?></p>
    </div>
</div>