<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this :
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
$sellerProfileDetails = $block->getSellerProfile ();
$sellerDetails = $sellerProfileDetails ['seller_details'];
$countryDatas = $sellerProfileDetails ['country_list'];
$logoImage = $sellerProfileDetails ['logo_image'];
$bannerImage = $sellerProfileDetails ['banner_image'];
$objectModelManager = \Magento\Framework\App\ObjectManager::getInstance ();
$customerSession = $objectModelManager->get('Magento\Customer\Model\Session');
?>

<form class="form form-edit-account " enctype="multipart/form-data"
    action="<?php  echo $block->getUrl('*/*/saveprofile')?>"
    method="post" id="seller_profile_validate"
    data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset"
        data-hasrequired="<?php  echo __('* Required Fields') ?>">
        <div class="field_store_logos">
            
            <div class="store_logos">
                <!--<label for="store_logo"><?php //echo __('Store Logo'); ?>  </label>
                <span class="market_place_image_sizes"><?php echo __('Upload image size 150 X 110'); ?></span>-->
                <?php if($sellerDetails->getLogoName()!=''){?>
                <div class="profile-image"><img src="<?php echo $logoImage.$sellerDetails->getLogoName(); ?>" alt="store logo" class="store_img" /></div>   
                <input type="checkbox" name="remove_logo" value="1"> <?php echo __('Remove'); ?>
                <?php }?>
                
                <input type="file" name="store_logo" class="store_logo" id="store_logo" /> 
                
                
                <div style="clear: both;"></div>
                
            </div>
            <label for="store_logo"><?php //echo __('Store Logo'); ?>  </label>
        </div>
        
        <div class="fields">
            <div class="field store_name required">
                <label for="store_name" class="label"><span><?php  echo __('Name') ?></span></label>
                <div class="control">
                    <input type="text" name="store_name"
                        alt="store_name" id="store_name"
                        value="<?php echo $sellerDetails->getStoreName();?>"
                        class="input-text"
                        data-validate="{required:true}" />
                </div>
            </div>
        </div>
        
        <div class="fields">
            <div class="field store_name required">
                <label for="store_name" class="label"><span><?php  echo __('Email') ?> </span> </label>
               
                <div class="control">
                     <input type="email" name="email-display" id="email" autocomplete="email" data-input="change-email" value="<?php echo $customerSession->getCustomer()->getEmail(); ?>" title="Email" class="input-text" aria-required="true" data-validate="{required:true}">
                </div>
            </div>
        </div>

        <div class="fields">
            <div class="field contact required">
                <label for="contact" class="label"><span><?php  echo __('Contact Number') ?></span></label>
                <div class="control">
                    <input type="text" name="contact"
                        value="<?php echo $sellerDetails->getContact();?>"
                        alt="Contact" id="contact" class="input-text"
                        data-validate="{required:true}" />
                    <div id="phoneerror"></div>
                </div>
            </div>
        </div>
        
        <div class="fields">
            <div class="field state required">
                <label for="state" class="label"><span><?php  echo __('State') ?></span></label>
                <div class="control">
                    <input type="text" name="state" alt="state"
                        value="<?php echo $sellerDetails->getState();?>"
                        id="state" class="input-text"
                        data-validate="{required:true,'validate-state':true}">
                </div>
                <div id="stateerror"></div>
            </div>
        </div>

        <div class="field country required">
            <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
                <select name="country" id="country" class="country"
                    title="Country"
                    data-validate="{'validate-select':true}">
                    <option value="">-- Please Select --</option>
                 <?php foreach ($countryDatas as $country) { ?>
                 <option value="<?php echo $country['country_id']; ?>"
                        <?php echo   $sellerDetails->getCountry() == $country['country_id'] ? ' selected="selected"' : ''; ?>>
                <?php
                  $countryModel = $objectModelManager->get ( 'Magento\Directory\Model\Country' );
                  $country = $countryModel->loadByCode ( $country ['country_id'] );
                  echo $country->getName ();
                  ?>
                </option>
                <?php } ?>
              </select>
            </div>
        </div>


        <div class="fields" >
            <div class="field address required">
                <label for="address" class="label"><span><?php  echo __('Address') ?></span></label>
                <div class="control">
                    <input alt="address" value="<?php echo strip_tags($sellerDetails->getAddress());?>" type="text" id="address" name="address"
                        title="address" class="input-text address" data-validate="{required:true}" />

                </div>
            </div>
        </div>
        <div class="fields">
            <div class="field company_description">
                <label for="company_description" class="label"><span><?php  echo __('Complement') ?></span></label>
                <input type="text" id=""
                    name="company_description"
                    title="company_description"
                    class="input-text companydesc"
                     value="<?php echo strip_tags($sellerDetails->getDesc());?>" />
            </div>
        </div>
        
        <div class="field choice" style="display: none;">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="Change Email" class="checkbox">
            <label class="label" for="change-email"><span>Change Email</span></label>
        </div>
        
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="Change Password" class="checkbox">
            <label class="label" for="change-password"><span>Change Password</span></label>
        </div>
        
        <div class="field email required" data-container="change-email" style="display: none;">
            <label class="label" for="email"><span>Email</span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?php echo $customerSession->getCustomer()->getEmail(); ?>" title="Email" class="input-text" aria-required="true" data-validate="{required:true}">
            </div>
        </div>
        <div class="field password current required" style="display: none;">
            <label class="label" for="current-password"><span>Current Password</span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" aria-required="true" data-validate="{required:true}">
            </div>
        </div>
        
        <div class="field new password required" data-container="new-password" style="display: none;">
            <label class="label" for="password"><span>New Password</span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password" data-password-min-length="8" data-password-min-character-sets="3" data-input="new-password" autocomplete="off" aria-required="true" data-validate="{required:true, 'validate-customer-password':true}">
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password" style="display: none;">
            <label class="label" for="password-confirmation"><span>Confirm New Password</span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-input="confirm-password" autocomplete="off" aria-required="true" data-validate="{required:true, equalTo:&quot;[data-input=new-password]&quot;}">
            </div>
        </div>
        
        <div class="field">
        <label class="label"></label>
        <div class="control">
        
        <button type="submit" class="button validation-passed"
            title="Save Profile" name="save_profile" id="save_profile">
            <span><span>Save Profile</span></span>
        </button>
        
        <button type="reset" class="button"
            title="Cancel Profile" name="reset_profile" id="reset_profile">
            <span><span>Cancel</span></span>
        </button>
        </div>
        </div>
        
        
    </fieldset>
</form>
<script>
require([
    'jquery',
    'mage/adminhtml/wysiwyg/tiny_mce/setup'
], function(jQuery){

var config = '',
    editor;

jQuery.extend(config, {
    settings: {
        theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,',
        theme_advanced_buttons2: null,
        theme_advanced_buttons3: null,
        theme_advanced_buttons4: null,
        theme_advanced_statusbar_location: null
    },
    files_browser_window_url: false
});
              editor = new tinyMceWysiwygSetup(
    'company_description',
    config
);
                           editor.turnOn();
                           jQuery('#company_description')
    .addClass('wysiwyg-editor')
    .data(
        'wysiwygEditor',
        editor
    );
 });
</script>
<script type="text/javascript">

     function updateShowProfileLink(){
        if(document.getElementById("show_profile_link").checked){
        document.getElementById("show_profile_link").value = 1;
        }else{
        document.getElementById("show_profile_link").value = 0;
        }
        }

      var logoFlag=1;
      var bannerFlag=1;
      var errFlag = false;
      require([
         'jquery',
         'mage/mage'
     ], function($){
   $('#errorlogomsg').hide();
   $('#errorbannermsg').hide();
   $("#phoneerror").hide();
   $("#store_logo").change(function(){
       if (!/(\.bmp|\.png|\.gif|\.jpg|\.jpeg)$/i.test(this.value)) {
       $("#store_logo").focus();
           $('#errorlogomsg').show();
           document.getElementById("errorlogomsg").innerHTML = "Invalid file format";
           $('#errorlogomsg').css("color","#e02b27");
           logoFlag=0;
          return false;

       }
        logoFlag=1;
       $('#errorlogomsg').hide();
     return true;
   });

   $("#store_banner").change(function(){
       if (!/(\.bmp|\.png|\.gif|\.jpg|\.jpeg)$/i.test(this.value)) {
       $("#store_banner").focus();
           $('#errorbannermsg').show();
           document.getElementById("errorbannermsg").innerHTML = "Invalid file format";
           $('#errorbannermsg').css("color","#e02b27");
            bannerFlag=0;
          return false;
   }
       bannerFlag=1;
       $('#errorbannermsg').hide();
      return true;
   });

   $("#seller_profile_validate").submit(function(){

   var telephoneNumber = $("#contact").val();
   var test_phone_number = /^(?=.*[0-9])[- +()0-9]+$/;
   if(!test_phone_number.test(telephoneNumber) ){
     $("#phoneerror").html("<?php echo __('Please fill correct telephone number'); ?>");
 $("#phoneerror").css("color", "#e02b27");
         $("#phoneerror").css("font-size", "1.2rem");
           errFlag = true;
     }
   else{
   errFlag = false;
   }

      var state = $("#state").val();
   var state_regex = /^[a-zA-Z ]*$/;
   if(!state_regex.test(state) ){
     $("#stateerror").html("<?php echo __('Please fill correct state'); ?>");
 $("#stateerror").css("color", "#e02b27");
         $("#stateerror").css("font-size", "1.2rem");

           stateFlag = true;

     }
      else{
   stateFlag = false;
       }

   if(stateFlag==1){
 $("#state").focus();
 return false;
}

    if(bannerFlag == 1 && logoFlag==1 && errFlag==false && stateFlag==false){
   return true;
         }
         else if(bannerFlag == 0){
        $("#store_banner").focus();
            return false;
         }
         else if(logoFlag ==0){
         $("#store_logo").focus();
         return false;
         }
         else if(errFlag == true){
         $("#contact").focus();
         $("#phoneerror").show();
         return false;
         }
         else{
         $("#store_logo").focus();
         return false;
         }
  });
});
</script>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
   var dataForm = $('#seller_profile_validate');
    var ignore = null;
    dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

});
</script>

<script type="text/javascript">
  require([ 'jquery','jquery/ui'], function($){
      jQuery('#country').chosen();
      


 
  
  
    jQuery('#change-password').change(function(){
    if($(this).is(":checked")) {
        $('.form-edit-account .password').css('display','block');
    } else {
       $('.form-edit-account .password').css('display','none'); 
    }
  });
   });  
  
</script>