
<div class="advance-searchn"> 
<?php
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    if(isset($_GET['concert_date'])){
            $from = $_GET['concert_date'];
            $date_from = $from['from'];
            $date_to = $from['to'];
            if($date_from==''){
                $date_from = '';
            }else{
                $date_range = $date_from;
            }
            if($date_to ==''){
                $date_to ='';
            }else{
                $date_range = $date_to;
            }
            $time = strtotime('10/16/2003');
$newformat = date('Y-m-d',$time);

            if($date_to !='' && $date_from!=''){
                $date_range = date('d/m/Y',strtotime($date_from)).' - '.date('d/m/Y',strtotime($date_to));
            }else{
                $date_range = '';
                            
            }
            
            //$adv_take= '06/1/2017 - 06/17/2017';
        }else{
            $date_from ='';
            $date_to ='';
            $date_range ='';
        }
        
        if(isset($_GET['price'])){
            $price = $_GET['price'];
            $price_to = $price['to'];
            $price_from = $price['from'];
            if($price_to==''){
                $price_to = '';
            }
            if($price_from==''){
                $price_from = '';
            }
            
        }else{
            $price_from = '';
            $price_to = '';
        }
        
        if(isset($_GET['cat'])){
            $cat = $_GET['cat'];
        }else if(!isset($_GET['cat'])){
            $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
            if($category){
                $cat = $category->getId();
            }else{
                $cat = '';
            }
        }else{
            $cat = '';
        }
        //echo $date_to.'=>'.$date_from.'=>'.$date_range;
    ?>
    
<form id="custom-form" class="form search advanced" action="<?php echo $this->getUrl('catalogsearch/advanced/result') ?>" method="get" enctype="multipart/form-data" class="form" >
<?php
            $attr_code = 'sexo';
            $attribute = $objectManager->create('\\Magento\\Catalog\\Model\\Product\\Attribute\\Repository')->get($attr_code);
            $options = $attribute->getOptions();
           
            if($options){
            $i = 0;
            echo '<div style="display:none">';
                foreach($options as $option){
                    if($i!=0){
                    $optionText = $option->getLabel();
                    $optionId = $attribute->getSource()->getOptionId($optionText);
                    if(isset($_GET['sexo'])){
                      $sex =  $_GET['sexo'];
                      foreach($sex as $v){
                        $arr[] = $v;
                      }
                    }else{
                        $arr[] = 0;
                    }
                    if(in_array($optionId, $arr)){
                         echo '<input type="checkbox" name="sexo[]" value="'.$optionId.'" id="option1'.$i.'" onChange="this.form.submit()" checked style="display:none"> ';       
                    }else{
                        echo '<input type="checkbox" name="sexo[]" value="'.$optionId.'" id="option1'.$i.'" onChange="this.form.submit()" style="display:none">';       
                    }
                    }
                $i++;
                }
            echo '</div>';
            }
        ?>
<input name="price[from]" type="hidden" placeholder="R$ 00.00" value="<?php echo $price_from;?>"/>
<input name="price[to]" type="hidden" placeholder="R$ 00.00" value="<?php echo $price_to;?>"/>
<input type="hidden" name="cat" id="cat" value="<?php echo $cat; ?>" />
<input type="hidden" name="concert_date[from]" id="date_from" value="<?php echo $date_from; ?>" />
<input type="hidden" name="concert_date[to]" id="date_to" value="<?php echo $date_to; ?>" />
    <!--<select name="busca_por_ingresso" class="chosen-select select-city" id="busca_por_ingresso"> 
    
      <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $attr_code = 'busca_por_ingresso';
        $attribute = $objectManager->create('\\Magento\\Catalog\\Model\\Product\\Attribute\\Repository')->get($attr_code);
        $options = $attribute->getOptions();
        if($options){
                        $select = 0;
                        $i = 0;
                       echo '<option value="">Busca por ingresso</option>';
                        foreach($options as $option){
                        if($i !=0){    
                    	$optionText = $option->getLabel();
                        $optionId = $attribute->getSource()->getOptionId($optionText);
                        if(isset($_GET[$attr_code])){
                            if($_GET[$attr_code] == $optionId){
                                $select = 1;
                            }else{
                                $select = 0;
                            }
                        }
                        
                    	if($select==1){
                    	   echo '<option value="'.$optionId.'" selected>'.$option->getLabel().'</option>';
                    	}else{
                    	echo '<option value="'.$optionId.'">'.$option->getLabel().'</option>';
                    	}
                
                        }
                        $i++;
                        }
                        
                    }
        
        
        ?>
    </select>-->
    
    <select class="chosen-select select-location" name="busca_por_cidade" id="busca_por_cidade" onchange="submit_form('busca_por_cidade')">
        <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $attr_code = 'busca_por_cidade';
            $attribute = $objectManager->create('\\Magento\\Catalog\\Model\\Product\\Attribute\\Repository')->get($attr_code);
            $options = $attribute->getOptions();
            if($options){
                $select = 0;
                $i = 0;
                        
                        echo '<option value="">Busca por cidade</option>';
                        foreach($options as $option){
                            if($i !=0){
                        	$optionText = $option->getLabel();
                            $optionId = $attribute->getSource()->getOptionId($optionText);
                            if(isset($_GET[$attr_code])){
                                if($_GET[$attr_code] == $optionId){
                                    $select = 1;
                                }else{
                                    $select = 0;
                                }
                            }
                            
                        	if($select==1){
                        	   echo '<option value="'.$optionId.'" selected>'.$option->getLabel().'</option>';
                        	}else{
                        	echo '<option value="'.$optionId.'">'.$option->getLabel().'</option>';
                            
                        	}  
                            }   
                            $i++;      
                        }
            }
        ?>
    </select>

    
    <div class="select-date">
        <input id="dtpicker" name="date" type="text" placeholder="Busca por data" onchange="" value="<?php echo $date_range; ?>"/>
    </div>
    
</form>
</div>
<script type="text/javascript">
  require([ 'jquery','jquery/ui'], function($){
    jQuery('.chosen-select').change(function(){

       if(jQuery(this).val()){
            //alert(jQuery(this).val());
            jQuery("#custom-form").submit();
       } 
    });
    
      jQuery('#sorter').chosen();
     

    
    jQuery("#dtpicker").daterange({
            dateFormat: 'dd/mm/yy',
            numberOfMonths: 2,
            showButtonPanel: true,
            
            //minDate: "dateToday",
        //defaultDate: "+5w",
            
            onClose: function (dateRangeText) {
                if(dateRangeText!=''){
                    
                
                var firstvalue = dateRangeText.split("-",1);
                var lastvalue = dateRangeText.split(/[\s,]+/);
                
                
                
                var dateString = dateRangeText;
                var dateParts = dateString.split("/");
                
                var firstvalue = dateParts[1]+'/'+dateParts[0]+'/'+dateParts[2].split(' -',1); // month is 0-based
                var lastvalue = dateParts[3]+'/'+dateParts[2].split(' - ')[1]+'/'+dateParts[4]; // month is 0-based
                
                
                //jQuery("#dtpicker").after("<p>" + lastvalue[lastvalue.length-1] + "</p>");
                //alert(firstvalue + " =>" + lastvalue);
                jQuery("#date_from").val(firstvalue);
                jQuery("#date_to").val(lastvalue);
                jQuery("#custom-form").submit();
                }
            }
        }); 
        jQuery('#dtpicker').data('daterangepicker').setStartDate('01/08/2017');
        jQuery('#dtpicker').datepicker({
      });
  });
</script>

