<div class="home_slider clearfix">
    <div id="homeslider" class="owl-carousel owl-theme">
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_slider')->toHtml();?>
    </div>
</div>
<script type="text/javascript">
    require([
    "jquery"
    ], function($){
        $(document).ready(function() {
            jQuery("#homeslider").owlCarousel({
                items: 1,
                autoplay: true,
                dots: true,
                nav: false,
                loop: false
            });
        });
    });
</script>