
<div class="advance-searchn"> 
<form name="" class="">
    <select class="select-location">
      <option value="Show">Show</option>
      <option value="Show">Show</option>
      <option value="Show">Show</option>
      <option value="Show">Show</option>
    </select>
    <select class="select-city">
      <option value="Show">Show</option>
      <option value="Show">Show</option>
      <option value="Show">Show</option>
      <option value="Show">Show</option>
    </select>
    <div class="select-date">
    <input id="d4" type="text" placeholder="Busca por data"/>
    </div>
</form>
</div>


<script type="text/javascript">
 require([
    "jquery"
    ], function($){
    $(document).ready(function() {
  $('.advance-searchn select, .advance-search select').selectric();

  });
  });
</script>

