<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="row contact-page">
    <div class="col-sm-6 left">
        <h3>Get in Touch</h3>
        <p>Need more informations? Feel free to contact us by leaving your personal particulars as well as message in the contact form to the right</p>
        
        <ul>
            <li class="user ">
                <i class="fa fa-user" aria-hidden="true"></i>
                <h4>Find us at the office</h4>
                <p>22 Sin Ming Lane #06-76,Midview City,
                <p>Singapore 573969.</p>
            </li>
            <li class="phone">
                <i class="fa fa-phone" aria-hidden="true"></i><strong></strong>
                <h4>Give us a ring</h4>
                <p>+65 6816 0147</p>
                <p>Mon-Fri, 9:30-18:00</p>
            </li>
            <li class="email">
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                <h4>Email us</h4>
                <p>enquiry@xanda.sg</p>
            </li>
        </ul>
    </div>
    
    <div class="col-sm-6 right">
        <form class="form contact"
          action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
          data-mage-init='{"validation":{}}'>
          <h6>CONTACT US</h6>
            <fieldset class="fieldset">
                <div class="field name required">
                    <div class="control">
                        <input placeholder="Name" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field telephone">
                    <div class="control">
                        <input placeholder="Phone" name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field email required">
                    <div class="control">
                        <input placeholder="Email" name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field comment required">
                    <div class="control">
                        <textarea placeholder="Your Message" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="7" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form.additional.info'); ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value="" />
                    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Your Message') ?>" class="action submit primary">
                        <span><?php /* @escapeNotVerified */ echo __('Send Your Message') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
