<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>

<div class="sale-topbar">
    <div class="sale-title"><?php echo __('Sold');?></div>
    <div class="sale-enable">
        <ul>
            <li><a id="enable-product" href="#"><?php echo __('All');?></a></li>
            <li><a href="#"><?php echo __('Pending');?></a></li>
            <li><a href="#"><?php echo __('Completed');?></a></li>
        </ul>
    </div>
</div>

<div class="order-manage">
   <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();   
        
        $productCollection = $block->getCollection ();
        if ($productCollection->getSize () > 0) {
    ?>
      <div class="toolbar top">
         <?php echo $block->getPagerHtml(); ?>
      </div>
    <div class="table-wrapper orders-history">
        <table class="manage-product-table data table table-order-items history"
            id="my-orders-table">
            <caption class="table-caption"><?php echo __('Orders');?></caption>
          <!--  <tr>
                <th></th>
                <th><?php echo __('Date');?></th>

                <th><?php echo __('Product Details');?></th>
                <th><?php echo __('Total Product Amount');?></th>
                <th><?php echo __('Commission');?></th>
                <th><?php echo __('Seller Amount');?></th>
                <th><?php echo __('Status');?></th>
                <th><?php echo __('Action');?></th>
            </tr> -->
                <?php
                    
                    foreach ( $productCollection as $product ) {
                    $orderId = $product->getOrderId ();
                    $sellerId = $product->getSellerId ();
                    $customerId = $product->getCustomerId ();
                    $orderDetails = $block->getOrderDetails ( $orderId, $sellerId, $customerId );
                    $getProductDetails = $block->getProductDetails ( $orderId, $sellerId );
                    $product_id = $block->getProductId($orderId, $sellerId);
                    $createdAt = $orderDetails ['created_at'];
                    $modifiedDate = new DateTime ( $createdAt );
                    $createdAt = $modifiedDate->format ( 'm/d/Y' );
                    $currencyCode = $product->getOrderCurrencyCode ();
                    $currencySymbol = $block->getCurrencySymbol ( $currencyCode );
                    if (empty ( $currencySymbol )) {
                    $currencySymbol = $currencyCode;
                    }
                     
                ?>   
                <tr>
                <td class="prd-image"> 
                <?php
                $imagehelper = $this->helper ( 'Magento\Catalog\Helper\Image' );
                $productImage = $imagehelper->init ( $product, 'category_page_list' )->constrainOnly ( FALSE )->keepAspectRatio ( TRUE )->keepFrame ( FALSE )->resize ( 200 )->getUrl ();
                
                $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
                 //echo $product->getThumbnail();
                $imagewidth=160;
                $imageheight=160;
                $imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
                $productImage = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize($imagewidth, $imageheight)->getUrl();

                
                ?> 
                <?php if($product->getStatus() == 1){?>
                <a href="<?php echo $product->getProductUrl(); ?>"
                                title="<?php echo $product->getName(); ?>"> <img
                                    src="<?php echo $productImage; ?>" />
                            </a>  <?php
                } else {
                    ?>
                <img src="<?php echo $productImage; ?>" />
                <?php }?>
                </td>
                <!--<td><?php echo $product->getIncrementId();?></td>-->
                <td class="prd-center"><?php echo $getProductDetails;?>
                    <div class="dp-wrap"> <div class="dp-date"><?php echo $createdAt;?> </div>
                    <div class="dp-price"><?php echo $currencySymbol.number_format($product->getSellerProductTotal(), 2, '.', '');  ?></div></div>
                    
                    <div class="mobile-option" style="display: none;">
                         <?php if ($product->getStatus () == 'refunded' && $orderDetails ['refund_flag'] != 1) {
                            ?> <div class="ord-complete"> <?php
                          echo __ ( 'Completed' ); ?> </div> <?php
                         } else {
                            
                            if (ucfirst ( $product->getStatus () ) == 'Completed'){
                                ?> <div class="ord-complete"> <?php
                          echo ucfirst ( $product->getStatus () ); ?> </div> <?php } else { ?> <div class="ord-pending"> <?php echo ucfirst ( $product->getStatus () );
                            
                          }
                          ?>
                          </div>
                          <?php
                         }
                         ?>                    
                        <div class="ord-view"><a href="<?php echo $block->getUrl('marketplace/order/vieworder/id/'.$orderId)?>" class="action view"> <span><?php echo __('View');?></span></a></div>
                    </div>
                 
                 </td>
                <!--<td></td>
                <td></td>
                <td><?php echo $currencySymbol.number_format($product->getCommission(),2, '.', ''); ?></td>
                <td><span class="price"><?php echo $currencySymbol.number_format($product->getSellerAmount(),2,'.', '');?></span></td>-->
                <td class="ord-status"><?php
                    if ($product->getStatus () == 'refunded' && $orderDetails ['refund_flag'] != 1) {
                        ?> <div class="ord-complete"> <?php
                      echo __ ( 'Completed' ); ?> </div> <?php
                     } else {
                        
                        if (ucfirst ( $product->getStatus () ) == 'Completed'){
                            ?> <div class="ord-complete"> <?php
                      echo ucfirst ( $product->getStatus () ); ?> </div> <?php } else { ?> <div class="ord-pending"> <?php echo ucfirst ( $product->getStatus () );
                        
                      }
                     }
                     ?>
                     
                </td>
                <td class="ord-view"><a href="<?php echo $block->getUrl('marketplace/order/vieworder/id/'.$orderId)?>" class="action view"> <span><?php echo __('View');?></span></a></td>
                </tr>
         <?php }?>    
      </table>
        <div class="toolbar-bottom">
            <div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
        </div>
    </div>
   <?php

} else {
    
    ?>
    <div class="no-record">
    <?php
    echo __ ( 'No Records were Found' );
    ?>
    </div>
    <?php
}
?>
</div>