<?php 
//    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
//    $_category  = $block->getCurrentCategory();
//    $_imgHtml   = '';
//    if ($_imgUrl = $_category->getImageUrl()) {
//        $_imgHtml = '<div class="category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($_category->getName()) . '" title="' . $block->escapeHtml($_category->getName()) . '" class="image" /></div>';
//        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
//        /* @escapeNotVerified */ echo $_imgHtml;
//    }
?>

<script type="text/javascript">
require([
    'jquery'
], function ($) {
    'use strict';
    jQuery(document).ready(function() {  
        if(jQuery(window).width() < 767 ){
            jQuery(".block-search").prependTo("#maincontent").wrap('<div class="mobile-search-block"></div>');
        }
    });                 
});
</script>