<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form clearfix">
    <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?php echo $block->getBlockHtml('formkey')?>
        <?php echo $block->getChildHtml('form_top'); ?>
        <?php if (!$block->hasOptions()):?>
            <?php echo $block->getChildHtml('product_info_form_content'); ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <?php echo $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>
        
        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?php echo $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?php echo $block->getChildHtml('form_bottom'); ?>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?php echo $block->escapeHtml($_product->getId())?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
    });
</script>

<div class="product-custom-attribute clearfix">
<ul>
<?php 
  $atrribute =  $_product->getResource()->getAttribute('opsommingbeschrijving')->getFrontend()->getValue($_product);
    if(! empty($atrribute)){
        $atrribute = explode(",",$atrribute);
        foreach($atrribute as $v){
            echo '<li><span class="icon-arrow"></span>'.$v.'</li>';
        }
    }
  ?>
</ul>
</div>

<div class="product-custom-plaag product-grid-down clearfix">
<?php 
$atrribute =  $_product->getResource()->getAttribute('plaag')->getFrontend()->getValue($_product);
if(!empty($atrribute)){
?>
<h3><?php echo __('For treatment of:') ?></h3>
<ul>
<?php 
  
    if(! empty($atrribute)){
        $atrribute = explode(",",$atrribute);
        foreach($atrribute as $v){
            echo '<li>'.$v.'</li>';
        }
    }
  ?>
</ul>
<?php } ?>
</div>

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('usp-productpage')->toHtml(); ?>